services:
  gea-alert:
    restart: unless-stopped
    image: "python:3-alpine3.22"
    working_dir: /gea
    volumes:
      - ./:/gea
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        pip install -r requirements.txt
        python -u main.py

  gea-web:
    restart: unless-stopped
    image: "busybox"
    working_dir: /gea
    volumes:
      - ./web:/gea
    entrypoint: ["busybox", "httpd", "-f", "-v"]
    ports:
      - ${PORT:-9080}:80
